### PR TITLE
fix: fix mtime precision on some filesystems

### LINKED ISSUE #82: Difference between lock.mtime and stat.mtime precision
Possibly related to #79 

We are still getting a lot of reports about stale locks, often on CI platforms (and docker). One possible cause might be users who are using Node <v9. It appears that in Node v9 there can be a difference in precision about the `lock.mtime` which is set with what `stat.mtime` reports back:

```js
updateLock 2019-03-23T09:30:18.519Z 2019-03-23T09:30:18.519Z                                                             10:30:33
precision ms                                                                                                             10:30:33
createdMtimeChecked 1553333418519 1553333418519                                                                          10:30:33
mtime set to 2019-03-23T09:30:33.523Z                                                                                    10:30:33
updateLock 2019-03-23T09:30:33.523Z 2019-03-23T09:30:33.000Z                                                             10:30:48
precision ms                                                                                                             10:30:48
createdMtimeChecked 1553333433523 1553333433000           
```
_(lines above are: <function.name> <lock.mtime> <stat.mtime>)_

After the last line the lock gets compromised due to the 523ms difference

-- edit --
I removed `Node v9` from the title because actually I am not sure if this is really a Node v9 issue only. It might very well be a Node v10+ issue as well which just doesnt show as often / repeatedly due to the general (performance) improvements made in v10+

### PR DESCRIPTION
**Pull request by satazor**
Closes #82, #87

### CODE REVIEW

**Comment by satazor** [comment]
Tests still need to be updated!

**Comment by satazor** [comment]
I ended up changing the strategy to a more robust one.

After acquiring the lock, I will probe the precision of the filesystem passed in `options.fs`. This will do a extra `utimes` syscall when compared to what is in master. But the probing will be made only **once** and it's value will be cached for the filesystem passed in `options.fs`.

This makes the code much more simple and easy to reason about.

**Comment by satazor** [comment]
@alanshaw @hugomrdias you may want to review this.

File: lib/mtime-precision.js [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+            callback(null, stat.mtime, precision);
+        });
+    });
+}
+
+function getMtime(precision) {
+    let now = Date.now();
+
+    if (precision === 's') {
+        now = Math.ceil(now / 1000) * 1000;
```
Comment (satazor) [inline lib/mtime-precision.js]: The fs might be either ceiling, rounding or flooring. `ceil` is preferred because of the `isStaleLock` check, where we are using a Date.now. This way, the mtime is always set a little bit in the future and the `isStaleLock` will always behave correctly. 

The fs might be either ceiling, rounding or flooring.
